FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /bardown-events-listener

COPY requirements.txt  /app/requirements.txt

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
RUN uv pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY . /app/

EXPOSE 3002

CMD ["uvicorn", "bardown_events_listener:app", "--host", "0.0.0.0", "--port", "3002"]
