name: clackamas-lacrosse-application

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: LaxDB
    ports:
      - "3306:3306"
      - "33060:33060"
    expose:
      - "3306"

  cache:
    image: valkey/valkey
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"
    depends_on:
      - db

  mq:
    image: rabbitmq:latest
    restart: always
    ports:
      - "15691:15691"
      - "15692:15692"
      - "25672:25672"
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
    expose:
      - "15691"
      - "15692"
      - "25672"
      - "4369"
      - "5671"
      - "5672"

  player-interface:
    image: player-interface
    build: ./src/player_interface/
    ports:
      - "3000:3000"
    depends_on:
      - cache

  player-data-service:
    image: player-data-service
    build: ./src/player_data_service/
    ports:
      - "3001:3001"
    depends_on:
      - player-interface

  bardown_events_listener:
    image: bardown-events-listener
    build: ./src/bardown_events_listener
    ports:
      - "3002:3002"
    depends_on:
      - mq
