FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /player-interface

COPY requirements.txt .

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
RUN uv pip install --no-cache-dir --upgrade -r /player-data-service/requirements.txt

COPY . .

EXPOSE 3000

CMD ["uvicorn", "main:player_interface.app", "--host", "0.0.0.0", "--port", "3000", "--workers", "1"]
