FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /player_interface

COPY requirements.txt /player_interface/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /player_interface/requirements.txt

COPY . /player_interface/

EXPOSE 3000

CMD ["uvicorn", "player_interface:app", "--host", "0.0.0.0", "--port", "3000"]