---
profile: local
db:
  host: "localhost"
  username: admin
  password: ${MYSQL_PASSWORD}
  root_password: ${MYSQL_ROOT_PASSWORD}
cache:
  host: "localhost"
  port: 6379
  password: ${REDIS_PASSWORD}
api:
  host: "localhost"
  port: 3001
  version: v0