FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /player-data-service

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade -r /player-data-service/requirements.txt

COPY . .

EXPOSE 3001

CMD ["uvicorn", "main:player_data_service.app", "--host", "0.0.0.0", "--port", "3001", "--workers", "1"]