---
name: Build Player Data Service
on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/ci_python.yaml"
      - "dev-requirements.txt"
      - "src/player_data_service/**"

jobs:
  build_player_data_service:
    uses: zfoteff/clackamas-lacrosse-application/.github/workflows/ci_python.yaml
    with:
      WORKING_DIR: ./src/player_data_service
      IMAGE_NAME: player_data_service
    secrets: inherit
