---
name: Build Player Interface
on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/ci_python.yaml"
      - "dev-requirements.txt"
      - "src/player_interface/**"

jobs:
  build_player_interface:
    uses: zfoteff/clackamas-lacrosse-application/.github/workflows/ci_python.yaml
    with:
      WORKING_DIR: ./src/player_interface/
      IMAGE_NAME: player_interface
    secrets: inherit
