---
name: Build Player Data Service
on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/ci_python.yaml"
      - "dev-requirements.txt"
      - "src/player_data_service/**"

jobs:
  build_player_data_service:
    uses: ./.github/workflows/ci_python.yaml
    with:
      working-dir: src/player_interface
    secrets: inherit