---
name: Build Project
on:
  workflow_dispatch:
    pull_request:
      push:
        branches: main
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
