---
name: Build Player Data Service
on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/ci_python.yaml"
      - "dev-requirements.txt"
      - "src/player_data_service/**"

jobs:
  get_version_number:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

  build_player_data_service:
    uses: ./.github/workflows/ci_python.yaml
    with:
      working_dir: ./src/player_interface
      image_name: player_interface
      image_tag:

    secrets: inherit

    electric fall air
    an uncertain world prepares,
    fantasy football
