---
name: Python Project CD
on:
  workflow_call:
    inputs:
      WORKING_DIR:
        description: "Working directory for the service being built and tested"
        required: true
        type: string
        default: "."

env:
  CONTAINER_REGISTRY: ghcr.io
  PACKAGE_REGISTRY: asdf

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIR }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        timeout-minutes: 5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: ${{ inputs.WORKING_DIR }}/requirements.txt
