---
name: Python CI
on:
  workflow_call:
    inputs:
      working-dir:
        required: true
        type: string
      install-packages:
        description: "Space-separated list of packages to install using apt-get."
        default: ""
        type: string
      image_name:
        description: "Name of the image to be published"

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    defaults:
      run:
        working-directory: ${{ inputs.working-dir }}
    
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Python
        uses: actions/setup-python@v4
        timeout-minutes: 5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install extra packages
        if: ${{ inputs.install-packages != ''}}
        run: |
          sudo apt-get install -y ${{ inputs.install-packages }}

      - name: Pip install dependencies
        run: |
          pip install -r requirements.txt

      - name: Test Python service
        run: |
          python3 -m pytest tests/

  containerize:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

  
  publish:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    needs:
      - build
    steps:
      - uses: actions/checkout@v4

      - name: Log into Container registry
        users: docker/login-action
        with:
          registry: ${{ env.REGISTRY }}
          username: $${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate metadata for Docker
        id: metadata
        uses: docker/metadata-action
        with:
          images: ${{ env.REGISTRY }}/${{ inputs.image_name }}

      - name: Push Docker Image
        id: push
        uses: docker/build-push-action


      - name: Publish Player Interface
        run: pwd
